services:
  - type: web
    name: lewlew-tshirt
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
